### PR TITLE
Simple Google Timezone API util

### PR DESCRIPTION
**Pull request by paololim**

### CODE REVIEW

**Comment by mbryzek** [comment]
is the idea to expose via a new resource that given an ip or text address would return a timezone?

**Comment by paololim** [comment]
This code is just the utility that can be used in either way.

Initial thought is to do something like this: https://github.com/flowcommerce/api/pull/373

**Comment by mbryzek** [comment]
minor comment but otherwise lgtm

**Comment by paololim** [comment]
Thanks. Updated the error message.

**Pull request merged**
